# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '51c91df1-b737-4398-8647-55cf4bcbd92f'
  imageRepository: 'himanshubectorjavacountriesassignment'
  containerRegistry: 'himanshuazurecicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/country-service/Dockerfile'
  tag: '$(Build.BuildId)'


pool: 
 name: 'azureagent'


stages:
- stage: MavenBuild
  displayName: Maven Build stage
  jobs:  
  - job: MavenBuild
    displayName: Build Maven Project
    steps:
    - task: Maven@4
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        goals: 'package'
- stage: DockerImageBuild
  displayName: Docker Image Build stage
  jobs:
  - job: DockerImageBuild
    displayName: Docker Image Build
    steps:
    - task: Docker@2
      displayName: Build the image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push stage
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push the image to Azure container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
