trigger:
- main

pool:
  name: 'azureagent'

variables:
  dockerRegistryServiceConnection: '51c91df1-b737-4398-8647-55cf4bcbd92f'
  imageRepository: 'himanshubectorjavacountriesassignment'
  containerRegistry: 'himanshuazurecicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/country-service/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: MavenAndDocker
    displayName: 'Maven and Docker Build'
    steps:
    - script: |
        wget https://apache.mirror.digitalpacific.com.au/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
        tar xzf apache-maven-3.8.4-bin.tar.gz -C /opt
        echo "export MAVEN_HOME=/opt/apache-maven-3.8.4" >> ~/.bashrc
        echo "export PATH=$PATH:/opt/apache-maven-3.8.4/bin" >> ~/.bashrc
        source ~/.bashrc
      displayName: 'Install Maven'

    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'country-service/pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
