
# Configure 'Deployment' of SpringBoot application

apiVersion: apps/v1
kind: Deployment

metadata:
  name: country-deployment

spec:
  selector:
    matchLabels:
      app: country-app

  replicas: 3

  template:
    metadata:
      labels:
        app: country-app

    spec:
      containers:
        - name: country-api-container
          image: himsb/country-service-api:1.0

          ports:
            - containerPort: 8080

---

# Define a 'Service' for the SpringBoot application

apiVersion: v1
kind: Service

metadata:
  name: country-service

spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  selector:
    app: country-app

  type: NodePort
